In [80]:
# 1ª CELULA

import os
import pandas as pd
from pathlib import Path
import numpy as np


# 2ª CELULA
separator = ";"
archivo = "MC1_INT_CSV_Clientes_Relacionados_2024_01_24_05_30_22.CSV"
path = Path("./")
path.mkdir(parents=True, exist_ok=True)

print('Pasta criada com sucesso!')

path_clientes_relacionados_2024_01_24_05_30_22 = r"./clientesrelacionados/" + archivo
clientesrelacionados_2024_01_24_05_30_22 = pd.read_csv(path_clientes_relacionados_2024_01_24_05_30_22, sep=separator)


clientesrelacionados_df =  pd.DataFrame({
    'Codigo_PDV': clientesrelacionados_2024_01_24_05_30_22['Codigo_PDV']
    ,'Codigo_Tipo_de_Negocio_PDV': clientesrelacionados_2024_01_24_05_30_22['Codigo_Tipo_de_Negocio_PDV']
    ,'Descripcion_Tipo_de_Negocio_PDV': clientesrelacionados_2024_01_24_05_30_22['Descripcion_Tipo_de_Negocio_PDV']
    ,'Codigo_Cluster_PDV': clientesrelacionados_2024_01_24_05_30_22['Codigo_Cluster_PDV']
    ,'Descripcion_Cluster_PDV': clientesrelacionados_2024_01_24_05_30_22['Descripcion_Cluster_PDV']
    })


clientes_relacionados_vacios = clientesrelacionados_df[
    
     clientesrelacionados_df.Codigo_Tipo_de_Negocio_PDV.isna() 
    | clientesrelacionados_df.Descripcion_Tipo_de_Negocio_PDV.isna()
    
    | clientesrelacionados_df.Codigo_Cluster_PDV.isna()
    #| clientesrelacionados_2024_01_24_05_30_22.Descripcion_Cluster_PDV.isna()
]   


clientes_relacionados_vacios = clientes_relacionados_vacios.set_index('Codigo_PDV')

type(clientes_relacionados_vacios)

display(clientes_relacionados_vacios)

Pasta criada com sucesso!

,Codigo_Tipo_de_Negocio_PDV,Descripcion_Tipo_de_Negocio_PDV,Codigo_Cluster_PDV,Descripcion_Cluster_PDV
Codigo_PDV,,,,
100081855,NaN,NaN,2,Potenciales
100081855,NaN,NaN,2,Potenciales
100090400,NaN,NaN,1,Estrategicos
100090400,NaN,NaN,1,Estrategicos
100075150,NaN,NaN,2,Potenciales
100075150,NaN,NaN,2,Potenciales
100094026,NaN,NaN,1,Estrategicos
100094026,NaN,NaN,1,Estrategicos
100101286,NaN,NaN,1,Estrategicos
100101286,NaN,NaN,1,Estrategicos
100122524,NaN,NaN,3,Transaccionales
100115306,NaN,NaN,3,Transaccionales
100115306,NaN,NaN,3,Transaccionales
100116442,NaN,NaN,2,Potenciales
100116442,NaN,NaN,2,Potenciales
100122524,NaN,NaN,3,Transaccionales
100119694,NaN,NaN,2,Potenciales
100119694,NaN,NaN,2,Potenciales
100135974,NaN,NaN,2,Potenciales
100135974,NaN,NaN,2,Potenciales
100139034,NaN,NaN,2,Potenciales
100139034,NaN,NaN,2,Potenciales
100719153,NaN,NaN,3,Transaccionales
100719153,NaN,NaN,3,Transaccionales
100779683,NaN,NaN,3,Transaccionales
100779683,NaN,NaN,3,Transaccionales
100227818,NaN,NaN,3,Transaccionales
100832034,NaN,NaN,3,Transaccionales
100832034,NaN,NaN,3,Transaccionales
100832605,NaN,NaN,3,Transaccionales
100832605,NaN,NaN,3,Transaccionales
100210115,NaN,NaN,2,Potenciales
100210115,NaN,NaN,2,Potenciales
100469962,NaN,NaN,3,Transaccionales
100216131,NaN,NaN,3,Transaccionales
100216131,NaN,NaN,3,Transaccionales
156102670,NaN,NaN,2,Potenciales
156102670,NaN,NaN,2,Potenciales
100110969,0.0,NaN,0,NaN
156104043,NaN,NaN,3,Transaccionales
156112700,NaN,NaN,2,Potenciales
156112700,NaN,NaN,2,Potenciales
156115173,NaN,NaN,2,Potenciales
156115173,NaN,NaN,2,Potenciales
156143636,NaN,NaN,2,Potenciales
156143636,NaN,NaN,2,Potenciales
156159790,NaN,NaN,3,Transaccionales
156159790,NaN,NaN,3,Transaccionales
156174168,NaN,NaN,3,Transaccionales
156174168,NaN,NaN,3,Transaccionales
156161373,NaN,NaN,3,Transaccionales
156161373,NaN,NaN,3,Transaccionales
100088965,NaN,NaN,3,Transaccionales
100088965,NaN,NaN,3,Transaccionales

In [35]:
clientes_relacionados_vacios.to_excel(r"./clientesrelacionados/Out/Clientes_Relacionados_Campos_Branco.xlsx")